### ISSUE TITLE
future road map and license issue

### ISSUE THREAD

**Issue by kunthar** [gootik/edeet#8]
Hiya,

Great work. 
1. We need to know about license type to decide contribute to the code or not. I personally prefer GPL 3. 
2. Road map. Do you have any road map? May be we can pick some items and complete them.

**Comment by gootik** [comment]
@kunthar Hi,
Thanks for the comment.
1. I'm fine with changing the License to something more restrictive like GPL.
2. That would be fantastic. This is obviously very early stage project, I've created a few high level issues that can be tackled. But over the next few days I'll be creating a more well thought out plan. 

To me the next most important things should be:
 1. Making the front end better at should who is editing what part of the document.
 2. Code cleanup, tests, and overall project structure.

Again, thanks for offering help. I think we need more projects like this in the Erlang community.
